image: golang:1.11

stages:
  - build
  - test

before_script:
  - apt-get -qq update
  - apt-get install -y libmagic-dev

build:
  stage: build
  script:
    - go build ./...

test:
  stage: test
  script:
    - test -z "$(gofmt -l . | tee /dev/stderr)"
    - go test ./...
