language: go
sudo: false

go:
  - 1.x
  - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libmagic-dev

install:
  - go get github.com/opennota/phash
  - go get github.com/mattn/go-sqlite3
  - go get github.com/rakyll/magicmime
  - go build ./...

script:
  - test -z "$(gofmt -l . | tee /dev/stderr)"
  - go test -v ./...

